//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.2.51 on Fri Dec 30 04:31:17 2016
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   x           0     NONE    uint       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
//
gs_4_0
dcl_input v[4][0].x
dcl_inputprimitive lineadj 
dcl_outputtopology pointlist 
dcl_output_siv o0.xyzw, position
dcl_maxout 144
mov o0.xyzw, l(0,0,0,0)
emit 
cut 
mov o0.xyzw, l(0,0,0,0)
emit_then_cut 
mov o0.xyzw, l(0,0,0,0)
emit 
cut 
ret 
// Approximately 0 instruction slots used
