//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.2.51 on Fri Dec 30 04:31:21 2016
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// SV_PrimitiveID           0    N/A   primID   PRIMID    uint    YES
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// m0:SV_Position           0   xyzw        0      POS   float   xyzw
// m0:TEXCOORD              0   xyzw        1     NONE   float   xyzw
// m0:SV_ClipDistance       0   x           2  CLIPDST   float   x   
// m0:SV_CullDistance       0    y          2  CULLDST   float    y  
// m0:SV_IsFrontFace        0   x           3    FFACE    uint   x   
// m0:SV_RenderTargetArrayIndex     0    y          3  RTINDEX    uint    y  
// m0:SV_ViewportArrayIndex     0     z         3  VPINDEX    uint     z 
// m1:SV_Position           0   xyzw        0      POS   float   xyzw
// m1:TEXCOORD              0   xyzw        1     NONE   float   xyzw
// m1:SV_ClipDistance       0   x           2  CLIPDST   float   x   
// m1:SV_CullDistance       0    y          2  CULLDST   float    y  
// m1:SV_IsFrontFace        0   x           3    FFACE    uint   x   
// m1:SV_RenderTargetArrayIndex     0    y          3  RTINDEX    uint    y  
// m1:SV_ViewportArrayIndex     0     z         3  VPINDEX    uint     z 
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_input_siv v[3][0].xyzw, position
dcl_input vGSInstanceID
dcl_input vPrim
dcl_temps 1
dcl_inputprimitive triangle 
dcl_stream m0
dcl_outputtopology pointlist 
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output_siv o2.x, clip_distance
dcl_output_siv o2.y, cull_distance
dcl_output_sgv o3.x, is_front_face
dcl_output_siv o3.y, rendertarget_array_index
dcl_output_siv o3.z, viewport_array_index
dcl_stream m1
dcl_outputtopology pointlist 
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output_siv o2.x, clip_distance
dcl_output_siv o2.y, cull_distance
dcl_output_sgv o3.x, is_front_face
dcl_output_siv o3.y, rendertarget_array_index
dcl_output_siv o3.z, viewport_array_index
dcl_maxout 3
mov o0.xyzw, l(0,0,0,0)
utof r0.x, vGSInstanceID.x
utof r0.y, vPrim
add r0.x, r0.y, r0.x
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_then_cut_stream m0
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_stream m1
cut_stream m1
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_stream m0
cut_stream m0
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_stream m1
cut_stream m1
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_stream m0
mov o0.xyzw, l(0,0,0,0)
mov o1.xyzw, r0.xxxx
mov o2.x, l(0)
mov o2.y, l(0)
mov o3.x, l(0)
mov o3.y, l(0)
mov o3.z, l(0)
emit_stream m1
ret 
// Approximately 0 instruction slots used
