//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.2.51 on Fri Dec 30 05:48:24 2016
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_resource_texture2d (float,float,float,float) t0
dcl_output o0.xyzw
dcl_temps 1
resinfo_indexable(texture2d)(float,float,float,float)_uint r0.xyz, l(0), t0.xywz
iadd r0.x, r0.y, r0.x
iadd r0.x, r0.z, r0.x
utof r0.x, r0.x
resinfo_indexable(texture2d)(float,float,float,float) r0.yzw, l(0), t0.zxyw
add r0.y, r0.z, r0.y
add r0.y, r0.w, r0.y
add o0.xyzw, r0.yyyy, r0.xxxx
resinfo_indexable(texture2d)(float,float,float,float)_rcpfloat r0.yzw, l(0), t0.zxyw
add r0.y, r0.z, r0.y
add r0.y, r0.w, r0.y
add o0.xyzw, r0.yyyy, r0.xxxx
ret 
// Approximately 0 instruction slots used
