//
// Generated by Microsoft (R) D3D Shader Disassembler
//
//   using 3Dmigoto v1.2.51 on Fri Dec 30 04:31:08 2016
//
//
// Note: shader requires additional functionality:
//       Shader extensions for 11.1
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed | enable11_1ShaderExtensions
dcl_uav_raw u0
dcl_temps 16
dcl_tgsm_raw g0, 4
dcl_thread_group 4, 2, 1
sync
sync_t
sync_g
sync_g_t
sync_sat_ugroup
sync_sat_ugroup_t
sync_sat_ugroup_g
sync_sat_ugroup_g_t
sync_uglobal
sync_uglobal_t
sync_uglobal_g
sync_uglobal_g_t
sync_sat_uglobal
sync_sat_uglobal_t
sync_sat_uglobal_g
sync_sat_uglobal_g_t
ret 
// Approximately 0 instruction slots used
