/* This file was autogenerated. Do not edit! */
#ifndef _INCL_MOJOSHADER_VERSION_H_
#define _INCL_MOJOSHADER_VERSION_H_
#define MOJOSHADER_VERSION 1146
#define MOJOSHADER_CHANGESET "hg-1146:31337471b909"
#endif

